/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:73691277-a36f-4be8-869b-490c6258b2a6",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_KeA2S5S4a",
    "aws_user_pools_web_client_id": "31v53v2os6c4fh0k5g96q24md2",
    "oauth": {}
};


export default awsmobile;
